import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Blog | Next App",
  description: "Generated by create next app",
};

async function getData() {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts", {
    // Параметры от Next,где указывается периодичность запроса/обновления,закеширования информации
    next: {
      revalidate: 60,
    },
  });
  return response.json();
}

export default async function Blog() {
  const posts = await getData();

  return (
    <>
      <h1>Blog page</h1>
      <ul>
        {posts.map((post: any) => (
          <li key={post.id}>
            <Link href={`/blog/${post.id}`}>{post.title}</Link>
          </li>
        ))}
      </ul>
    </>
  );
}
